### ISSUE TITLE
Not working with React - Expecting assignment or function call

### ISSUE THREAD

**Issue by MikeSilverstone** [tengbao/vanta#30]
Hi. This isn't working with React currently. Here is the stack trace:

./src/Components/vanta.globe.min.js
  Line 1:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:    'define' is not defined                                                no-undef

**Comment by MikeSilverstone** [comment]
Managed to get this working by using the unminified code and adding /* eslint-disable */ to the top of three.min.js.

Think this might be a problem with eslint and minified code.

**Comment by chandan-reddy-k** [comment]
@MikeSilverstone Can you please share the exact steps to get this working. Despite using unminified  version and disabling eslint, I was not able succeed : (

**Comment by tengbao** [comment]
@MikeSilverstone Thanks for the heads-up about `eslint-disable`. 
I've also updated the codebase to allow a custom THREE build, in case you're importing it from npm.

A working react example: 
1. run `create-react-app` (https://github.com/facebook/create-react-app)
2. copy the latest `vanta.globe.min.js` to `/src`
3. add  `/* eslint-disable */` to the top of `vanta.globe.min.js`
4. use this code for `App.js`:
```
import React from 'react'
import logo from './logo.svg'
import './App.css'
import * as THREE from 'three'
import GLOBE from './vanta.globe.min.js'

class App extends React.Component {
  constructor() {
    super()
    this.vantaRef = React.createRef()
  }
  componentDidMount() {
    this.vantaEffect = GLOBE({
      el: this.vantaRef.current,
      THREE: THREE
    })
  }
  componentWillUnmount() {
    if (this.vantaEffect) {
      this.vantaEffect.destroy()
    }
  }
  render() {
    return <div className="App">
      <header className="App-header" ref={this.vantaRef}>
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  }
}

export default App;
```

5. run `npm start`, go to `localhost:3000`

**Comment by tengbao** [comment]
@MikeSilverstone Thanks for the heads-up about `eslint-disable`. 
I've also updated the codebase to allow a custom THREE build, in case you're importing it from npm.

@chandan-reddy-k A working react example: 
1. run `create-react-app` (https://github.com/facebook/create-react-app)
2. copy the latest `vanta.globe.min.js` to `/src`
3. add  `/* eslint-disable */` to the top of `vanta.globe.min.js`
4. use this code for `/src/App.js`:
```
import React from 'react'
import logo from './logo.svg'
import './App.css'
import * as THREE from 'three'
import GLOBE from './vanta.globe.min.js'

class App extends React.Component {
  constructor() {
    super()
    this.vantaRef = React.createRef()
  }
  componentDidMount() {
    this.vantaEffect = GLOBE({
      el: this.vantaRef.current,
      THREE: THREE
    })
  }
  componentWillUnmount() {
    if (this.vantaEffect) {
      this.vantaEffect.destroy()
    }
  }
  render() {
    return <div className="App">
      <header className="App-header" ref={this.vantaRef}>
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  }
}

export default App;
```

5. run `npm install`, `npm start`, and go to `localhost:3000`

**Comment by maximebergerard** [comment]
Hi @tengbao, 
I've tried your _working exemple_ and it works perfectly well for the **Globe** or the **Waves Effect** but it doesn't work for the **Fog Effect**, displaying this error :

> TypeError: Cannot read property 'domElement' of undefined

Or for the **Cells Effect** displaying only the background color and :

> [VANTA] Init error ReferenceError: THREE is not defined

Do you have any ideas what that could be ? Thanks man !

**Comment by tengbao** [comment]
@maximebergerard Fixed in 3b0a9ea9ec91d8200d8bb4686c14ad30c7939e20
Please try again!

**Comment by chandan-reddy-k** [comment]
Hey @tengbao thanks for the example. This was the error I am facing. `TypeError: Cannot read property 'Geometry' of undefined` while trying to use `vanta.birds.min.js`

**Comment by jasontheiler** [comment]
Hi @tengbao,
I tried using the **NET effect** in my Create React App project like you describe in the [README.md](https://github.com/tengbao/vanta/blob/master/README.md). I tried both the React Hooks and the React Classes method. At first I ran into the same error as described by @MikeSilverstone, but adding `/* eslint-disable */` helped getting rid of the error. Afterwards I always ended up with a `TypeError: this.el is undefined`, though.

Console output:
```
[VANTA] Instance needs "el" param! index.js:1
TypeError: this.el is undefined net.js:181
The above error occurred in the <Hero> component:
    in Hero (at app.jsx:22)
    in div (at app.jsx:13)
    in App (at src/index.jsx:6)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. index.js:1
TypeError: this.el is undefined net.js:181
```

I then tried using it in a freshly created Create React App project. But then I ended up with a `TypeError: this.renderer is undefined`.

Console output:
```
[VANTA] No THREE defined on window vanta.net.min.js:2
[VANTA] Init error TypeError: "n.Group is not a constructor"
    onInit vanta.net.min.js:2
    init vanta.net.min.js:2
    <anonymous> vanta.net.min.js:2
    r vanta.net.min.js:2
    t vanta.net.min.js:2
    App App.js:13
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 3
    workLoop scheduler.development.js:641
    flushWork scheduler.development.js:596
    performWorkUntilDeadline scheduler.development.js:203
index.js:1
TypeError: this.renderer is undefined vanta.net.min.js:2
The above error occurred in the <App> component:
    in App (at src/index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. index.js:1
TypeError: this.renderer is undefined vanta.net.min.js:2

```

This error persists even though my code is exactly identical to the solution you proposed above.
(Except I tried using the **NET effect** instead of the **GLOBE effect**.)

App.js:
```
import React from "react";
import logo from "./logo.svg";
import "./App.css";
import * as THREE from "three";
import NET from "./vanta.net.min.js";

class App extends React.Component {
  constructor() {
    super();
    this.vantaRef = React.createRef();
  }
  componentDidMount() {
    this.vantaEffect = NET({
      el: this.vantaRef.current,
      THREE: THREE
    });
  }
  componentWillUnmount() {
    if (this.vantaEffect) {
      this.vantaEffect.destroy();
    }
  }
  render() {
    return (
      <div className="App">
        <header className="App-header" ref={this.vantaRef}>
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;

```

I would also greatly appreciate it, if you turned vantajs into an npm package! It would be much easier to set it up this way.

**Comment by jafetmorales** [comment]
I get `TypeError: Cannot read property 'Geometry' of undefined while trying to use vanta.birds.min.js` but I do not get it when using others like globe.

**Comment by tengbao** [comment]
@jafetmorales it seems like THREE isn't defined for you. Have you tried the `Using THREE from npm` section of the readme?

**Comment by tengbao** [comment]
@jasontheiler I've published vanta to npm. `npm i vanta`, then you can import an effect like this: 
`import VantaClouds from 'vanta/src/vanta.clouds'`

https://www.npmjs.com/package/vanta

**Comment by tengbao** [comment]
@jasontheiler I've published vanta to npm. `npm i vanta`, then you can import an effect like this: 
`import VantaClouds from 'vanta/dist/vanta.clouds.min'`

https://www.npmjs.com/package/vanta

**Comment by AmrViernes** [comment]
@tengbao Thanks man for the awesome work but it seem Birds really not working.

**Comment by jonra1993** [comment]
Hello guys I had similar problem but I was missing to add THREE. This code using hooks and BIRDS EFFECT worked for me.

import React, { useState, useEffect, useRef } from 'react'
import BIRDS from 'vanta/dist/vanta.birds.min'
import * as THREE from 'three'

const MyComponent = (props) => {
  const [vantaEffect, setVantaEffect] = useState(0)
  const myRef = useRef(null)
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(BIRDS({
       THREE,
        el: myRef.current
      }))
    }
    return () => {
      if (vantaEffect) vantaEffect.destroy()
    }
  }, [vantaEffect])
  return <div ref={myRef}>
    Foreground content goes here
  </div>
}

**Comment by Ravenink** [comment]
@tengbao, I've installed vanta through npm and I'm trying to make it work with React. Facing a similar error as the ones described here. When I try to use fog, I get this error message:

Uncaught TypeError: Cannot read properties of undefined (reading 'Color')
    at new r (vanta.fog.min.js:1:1)
    at new n (vanta.fog.min.js:1:1)
    at r.<computed> (vanta.fog.min.js:1:1)
    at fog.js:10:1

**Comment by Ravenink** [comment]
Thanks @jonra1993 your solution worked perfectly fine. I guess the example code in Vanta is simply wrong then!

**Comment by pr0mming** [comment]
I had the same error in React Hooks, but I have noticed this works with specific ThreeJS version, I use the same solution in the README:

`const [vantaEffect, setVantaEffect] = useState(0)
  const myRef = useRef(null)
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(WAVES({
        el: myRef.current,
        mouseControls: true,
        touchControls: true,
        gyroControls: false,
        minHeight: 200.00,
        minWidth: 200.00,
        scale: 1.00,
        scaleMobile: 1.00,
        color: 0x1d1d1e,
        shininess: 19.00
      }))
    }
    return () => {
      if (vantaEffect) vantaEffect.destroy()
    }
  }, [vantaEffect])

 return (
    <div className="App">      
      <section className="App-content" ref={myRef}>
     </section>
  </div>);`

With the r124 ThreeJS version: https://cdnjs.com/libraries/three.js/r124

If I try with superior version than r124 no works...
